import express from 'express';
import { UserRouter } from './user.route.js';
import { serviceProviderRouter } from './serviceProvide.route.js';
import { SupportRouter } from './support.route.js';
import { serviceRouter } from './service.route.js';
import { stateRouter } from './state.route.js';
import { OrderRouter } from './order.route.js';
import { OTPRouter } from './otp.route.js';
import { cityRouter } from './city.route.js';
import { categoryRouter } from './category.route.js';
import { cartRouter } from './cart.route.js';
import { addressRouter } from './address.route.js';
import { adminRouter } from './admin.route.js';
import { RatingRouter } from './rating.route.js';
import { walletRouter } from './wallet.route.js';
const router = express.Router();
const version = '/v1';
router.use(`${version}/admin`, adminRouter);
router.use(`${version}/address`, addressRouter);
router.use(`${version}/cart`, cartRouter);
router.use(`${version}/category`, categoryRouter);
router.use(`${version}/city`, cityRouter);
router.use(`${version}/otp`, OTPRouter);
router.use(`${version}/order`, OrderRouter);
router.use(`${version}/rating`, RatingRouter);
router.use(`${version}/state`, stateRouter);
router.use(`${version}/service`, serviceRouter);
router.use(`${version}/service-provider`, serviceProviderRouter);
router.use(`${version}/support`, SupportRouter);
router.use(`${version}/user`, UserRouter);
router.use(`${version}/wallet`, walletRouter);

export { router };
