name: D2D CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node js
      uses: actions/checkout@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependecy
      run: npm ci
    - name: Deploy to AWS
      run: |
        ssh user@your-ec2-instance-ip "cd /path/to/your/app && git pull origin main && npm install && pm2 restart server"
      
