name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p nodejs --region us-east-1  # Initialize Elastic Beanstalk if not already done
          eb deploy --staged --verbose
