name: Node.js CI/CD to AWS EC2

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: self-hosted  # This will use the GitHub runner installed on your AWS EC2 instance
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to AWS EC2
        run: |
           pm2 restart your-app"

