name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI and eb CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
          pip install --upgrade --user awsebcli

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p nodejs --region us-east-1 && eb deploy --staged --verbose
