name: D2D CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node js
      uses: actions/checkout@v4
      with:
        node-version: '20.15.1'
        cache: 'npm'
        
    - name: Install dependecy
      run: npm ci
    - name: Deploy to AWS
      run: |
        touch .env
        echo "${{secrets.env}}" > .env
      
